class freighthop::params {
  $packages                = []
  $ppas                    = []
  $languages               = []
  $ruby_version            = '1.9.3-p392'
  $app_name                = $::hostname
  $app_root                = "/srv/${app_name}"
  $web_servers             = ['nginx']
  $web_root                = "${app_root}/public"
  $http_port               = 80
  $https_port              = 443
  $upstream_port           = 3000
  $server_name             = $::fqdn
  $ssl                     = true
  $ssl_cert_path           = "/etc/ssl/certs/${app_name}.pem"
  $ssl_key_path            = "/etc/ssl/private/${app_name}.key"
  $uid                     = $::freighthop_uid
  $gid                     = $::freighthop_gid
  $passenger               = false
  $passenger_buffer_upload = false
}
